[package]
name = "jwt-encde"
version = "0.1.1"
edition = "2024"

[dependencies]
jsonwebtoken = "9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
iced = "0.14"
base64 = "0"
