[package]
name = "jwt-encde"
version = "0.2.0"
edition = "2024"

description = "GUI JWT encoder / decoder - Local, private, easy."
authors = ["nabbisen <nabbisen@scqr.net>"]
license = "Apache-2.0"

categories = ["development-tools"]
keywords = ["jwt", "auth", "test", "encrytion", "security"]
repository = "https://github.com/nabbisen/jwt-encde"
readme = "README.md"
rust-version = "1.87.0"

[dependencies]
jsonwebtoken = "9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
iced = "0.14"
base64 = "0"
json5 = "1"
